In [1]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler

In [2]:
wine = load_wine()
X = pd.DataFrame(data=wine.data, columns=wine.feature_names)

y = pd.Series(wine.target).rename('target').apply(lambda x: wine.target_names[x])

print(f'X shape: {X.shape}\ny shape: {y.shape}\nUnique targets: {wine.target_names}')

data = pd.concat([X,y], axis=1)
data

X shape: (178, 13)
y shape: (178,)
Unique targets: ['class_0' 'class_1' 'class_2']

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,class_0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,class_0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,class_0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,class_0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,class_0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,class_2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,class_2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,class_2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,class_2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,class_2

In [3]:
X_scaled = StandardScaler().fit_transform(X)
pd.DataFrame(X_scaled)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1.518613,-0.562250,0.232053,-1.169593,1.913905,0.808997,1.034819,-0.659563,1.224884,0.251717,0.362177,1.847920,1.013009
1,0.246290,-0.499413,-0.827996,-2.490847,0.018145,0.568648,0.733629,-0.820719,-0.544721,-0.293321,0.406051,1.113449,0.965242
2,0.196879,0.021231,1.109334,-0.268738,0.088358,0.808997,1.215533,-0.498407,2.135968,0.269020,0.318304,0.788587,1.395148
3,1.691550,-0.346811,0.487926,-0.809251,0.930918,2.491446,1.466525,-0.981875,1.032155,1.186068,-0.427544,1.184071,2.334574
4,0.295700,0.227694,1.840403,0.451946,1.281985,0.808997,0.663351,0.226796,0.401404,-0.319276,0.362177,0.449601,-0.037874
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,0.876275,2.974543,0.305159,0.301803,-0.332922,-0.985614,-1.424900,1.274310,-0.930179,1.142811,-1.392758,-1.231206,-0.021952
174,0.493343,1.412609,0.414820,1.052516,0.158572,-0.793334,-1.284344,0.549108,-0.316950,0.969783,-1.129518,-1.485445,0.009893
175,0.332758,1.744744,-0.389355,0.151661,1.422412,-1.129824,-1.344582,0.549108,-0.422075,2.224236,-1.612125,-1.485445,0.280575
176,0.209232,0.227694,0.012732,0.151661,1.422412,-1.033684,-1.354622,1.354888,-0.229346,1.834923,-1.568252,-1.400699,0.296498
177,1.395086,1.583165,1.365208,1.502943,-0.262708,-0.392751,-1.274305,1.596623,-0.422075,1.791666,-1.524378,-1.428948,-0.595160

In [4]:
pca = PCA()
X_pca = pca.fit_transform(X_scaled)

In [5]:
X_stdz = pd.DataFrame()
for col in X.columns:
	X_stdz[col] = X[col].apply(lambda x: (x - np.mean(X[col])) / np.std(X[col]))

# are_they_close = np.allclose(X_stdz, X_scaled)
# print(f'Are the manual and X_scaled matrices the same? {are_they_close}')
# for standardizing the data (x - x_bar) / stdev

X_stdz

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,1.518613,-0.562250,0.232053,-1.169593,1.913905,0.808997,1.034819,-0.659563,1.224884,0.251717,0.362177,1.847920,1.013009
1,0.246290,-0.499413,-0.827996,-2.490847,0.018145,0.568648,0.733629,-0.820719,-0.544721,-0.293321,0.406051,1.113449,0.965242
2,0.196879,0.021231,1.109334,-0.268738,0.088358,0.808997,1.215533,-0.498407,2.135968,0.269020,0.318304,0.788587,1.395148
3,1.691550,-0.346811,0.487926,-0.809251,0.930918,2.491446,1.466525,-0.981875,1.032155,1.186068,-0.427544,1.184071,2.334574
4,0.295700,0.227694,1.840403,0.451946,1.281985,0.808997,0.663351,0.226796,0.401404,-0.319276,0.362177,0.449601,-0.037874
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,0.876275,2.974543,0.305159,0.301803,-0.332922,-0.985614,-1.424900,1.274310,-0.930179,1.142811,-1.392758,-1.231206,-0.021952
174,0.493343,1.412609,0.414820,1.052516,0.158572,-0.793334,-1.284344,0.549108,-0.316950,0.969783,-1.129518,-1.485445,0.009893
175,0.332758,1.744744,-0.389355,0.151661,1.422412,-1.129824,-1.344582,0.549108,-0.422075,2.224236,-1.612125,-1.485445,0.280575
176,0.209232,0.227694,0.012732,0.151661,1.422412,-1.033684,-1.354622,1.354888,-0.229346,1.834923,-1.568252,-1.400699,0.296498
177,1.395086,1.583165,1.365208,1.502943,-0.262708,-0.392751,-1.274305,1.596623,-0.422075,1.791666,-1.524378,-1.428948,-0.595160

In [6]:
cov_mat = (X_stdz.T @ X_stdz) / (X_stdz.shape[0] - 1) # or X_stdz.cov()
# refer: https://askfilo.com/user-question-answers-smart-solutions/formulas-in-multivariate-statistics-3337333431333038

# are_they_close = np.allclose(cov_mat, X_stdz.cov())
# print(f"Are the manual and np.cov matrices the same? {are_they_close}\n")

cov_mat

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
alcohol,1.005650,0.094930,0.212740,-0.311988,0.272328,0.290734,0.238153,-0.156810,0.137470,0.549451,-0.072153,0.072752,0.647357
malic_acid,0.094930,1.005650,0.164972,0.290130,-0.054883,-0.337061,-0.413329,0.294632,-0.221993,0.250392,-0.564467,-0.370794,-0.193095
ash,0.212740,0.164972,1.005650,0.445872,0.288206,0.129708,0.115727,0.187283,0.009706,0.260350,-0.075089,0.003933,0.224890
alcalinity_of_ash,-0.311988,0.290130,0.445872,1.005650,-0.083804,-0.322928,-0.353355,0.363966,-0.198442,0.018838,-0.275503,-0.278332,-0.443086
magnesium,0.272328,-0.054883,0.288206,-0.083804,1.005650,0.215613,0.196890,-0.257742,0.237776,0.201080,0.055711,0.066377,0.395573
total_phenols,0.290734,-0.337061,0.129708,-0.322928,0.215613,1.005650,0.869448,-0.452477,0.615873,-0.055448,0.436132,0.703904,0.500929
flavanoids,0.238153,-0.413329,0.115727,-0.353355,0.196890,0.869448,1.005650,-0.540939,0.656379,-0.173353,0.546549,0.791641,0.496985
nonflavanoid_phenols,-0.156810,0.294632,0.187283,0.363966,-0.257742,-0.452477,-0.540939,1.005650,-0.367912,0.139843,-0.264123,-0.506113,-0.313144
proanthocyanins,0.137470,-0.221993,0.009706,-0.198442,0.237776,0.615873,0.656379,-0.367912,1.005650,-0.025393,0.297214,0.522000,0.332283
color_intensity,0.549451,0.250392,0.260350,0.018838,0.201080,-0.055448,-0.173353,0.139843,-0.025393,1.005650,-0.524761,-0.431238,0.317886
hue,-0.072153,-0.564467,-0.075089,-0.275503,0.055711,0.436132,0.546549,-0.264123,0.297214,-0.524761,1.005650,0.568663,0.237518
od280/od315_of_diluted_wines,0.072752,-0.370794,0.003933,-0.278332,0.066377,0.703904,0.791641,-0.506113,0.522000,-0.431238,0.568663,1.005650,0.314528
proline,0.647357,-0.193095,0.224890,-0.443086,0.395573,0.500929,0.496985,-0.313144,0.332283,0.317886,0.237518,0.314528,1.005650

In [7]:
eigen_vals, eigen_vecs = np.linalg.eig(cov_mat)
eigen_vals.tolist()

[4.732436977583593,
 2.5110809296451215,
 1.4542418678464684,
 0.9241658668248749,
 0.8580486765371099,
 0.6452822124678538,
 0.5541414662457835,
 0.10396199182075266,
 0.3504662749462542,
 0.16972373898012116,
 0.29051203269397713,
 0.22706428173088478,
 0.2523200103608246]

In [8]:
sorted_idx = np.argsort(eigen_vals)[::-1]
sorted_idx

array([ 0,  1,  2,  3,  4,  5,  6,  8, 10, 12, 11,  9,  7])

In [9]:
sorted_eigen_vals = eigen_vals[sorted_idx]
sorted_eigen_vecs = eigen_vecs[sorted_idx]

In [10]:
explained_var_ratio = sorted_eigen_vals / sorted_eigen_vals.sum()

# are_they_close = np.allclose(explained_var_ratio, pca.explained_variance_ratio_)
# print(f"Are the manual and pca.explained_variance_ratio_ matrices the same? {are_they_close}\n")
# for verification of the manual computation against the built-in fns

explained_var_ratio.tolist()

[0.36198848099926345,
 0.1920749025700892,
 0.11123630536249993,
 0.07069030182714037,
 0.06563293679648592,
 0.04935823319222562,
 0.04238679322623321,
 0.02680748948378867,
 0.02222153404789712,
 0.019300190939440767,
 0.017368356899899132,
 0.012982325756042109,
 0.007952148898994475]

In [11]:
explained_variance = pd.DataFrame({
    'Principal Component': [f'PC{_}' for _ in sorted_idx],
    'Variance Ratio': explained_var_ratio,
    'Cumulative Variance': np.cumsum(explained_var_ratio)
})
explained_variance.index += 1
explained_variance

   Principal Component  Variance Ratio  Cumulative Variance
1                  PC0        0.361988             0.361988
2                  PC1        0.192075             0.554063
3                  PC2        0.111236             0.665300
4                  PC3        0.070690             0.735990
5                  PC4        0.065633             0.801623
6                  PC5        0.049358             0.850981
7                  PC6        0.042387             0.893368
8                  PC8        0.026807             0.920175
9                 PC10        0.022222             0.942397
10                PC12        0.019300             0.961697
11                PC11        0.017368             0.979066
12                 PC9        0.012982             0.992048
13                 PC7        0.007952             1.000000

In [13]:
N_COMPONENTS_TO_KEEP = 9

principal_components = sorted_eigen_vecs[0:N_COMPONENTS_TO_KEEP]

X_new = X_stdz @ principal_components.T

print(f"Original data shape: {X_scaled.shape}")
print(f"New transformed data shape: {X_new.shape}")

Original data shape: (178, 13)
New transformed data shape: (178, 9)

In [15]:
X_new

,0,1,2,3,4,5,6,7,8
0,-0.796724,0.944879,-1.425941,2.361789,0.286795,-1.440448,-0.510404,-0.428741,-1.369433
1,-0.371087,0.976202,-1.479763,0.225152,-1.222941,0.055819,0.775285,-0.119008,-2.163259
2,0.701963,0.061657,0.157334,2.348014,-0.492888,-1.385939,-0.086779,0.109209,-0.133077
3,0.391606,1.142748,-0.662049,2.229725,0.060394,-2.265798,-0.394207,-1.801494,-1.517694
4,-0.489727,0.300401,1.230222,1.670558,1.010294,-0.078683,-0.305706,-0.323495,-0.012013
...,...,...,...,...,...,...,...,...,...
173,1.341910,0.659959,1.348168,-0.875653,1.526295,0.577467,-1.243247,0.473520,-0.456460
174,0.780966,-0.088460,1.072220,-0.710252,1.557502,-0.286938,-0.738105,0.438517,0.456956
175,0.631513,0.273903,0.038419,-1.093298,2.427083,-0.590316,-0.844729,0.893019,-0.103848
176,-0.017942,-0.056742,-0.105076,-0.810285,1.944656,-0.167801,-1.426183,1.078199,0.442700
177,0.526138,0.437255,1.935018,-0.119867,1.547274,0.050174,-1.777022,-0.322294,1.137258